# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\NIS3364-ChatRoom\client\resource\ui\ChatRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatRoom(object):
    def setupUi(self, ChatRoom):
        ChatRoom.setObjectName("ChatRoom")
        ChatRoom.resize(875, 627)
        self.listWidget = ListWidget(ChatRoom)
        self.listWidget.setGeometry(QtCore.QRect(25, 30, 221, 541))
        self.listWidget.setObjectName("listWidget")
        self.plainTextEdit = PlainTextEdit(ChatRoom)
        self.plainTextEdit.setGeometry(QtCore.QRect(280, 410, 561, 161))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = PlainTextEdit(ChatRoom)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(280, 30, 561, 341))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.toolButton = TransparentToolButton(ChatRoom)
        self.toolButton.setGeometry(QtCore.QRect(280, 380, 24, 22))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = TransparentToolButton(ChatRoom)
        self.toolButton_2.setGeometry(QtCore.QRect(320, 380, 24, 22))
        self.toolButton_2.setObjectName("toolButton_2")
        self.pushButton = PushButton(ChatRoom)
        self.pushButton.setGeometry(QtCore.QRect(754, 580, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.toolButton_3 = TransparentToolButton(ChatRoom)
        self.toolButton_3.setGeometry(QtCore.QRect(820, 380, 24, 22))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = TransparentToolButton(ChatRoom)
        self.toolButton_4.setGeometry(QtCore.QRect(360, 380, 24, 22))
        self.toolButton_4.setObjectName("toolButton_4")


        self.toolButton.setIcon(FluentIcon.GAME)
        self.toolButton_2.setIcon(FluentIcon.FOLDER)
        self.toolButton_4.setIcon(FluentIcon.MICROPHONE)
        self.toolButton_3.setIcon(FluentIcon.SYNC)


        self.retranslateUi(ChatRoom)
        QtCore.QMetaObject.connectSlotsByName(ChatRoom)

    def retranslateUi(self, ChatRoom):
        _translate = QtCore.QCoreApplication.translate
        ChatRoom.setWindowTitle(_translate("ChatRoom", "Form"))
        self.toolButton.setText(_translate("ChatRoom", ""))
        self.toolButton_2.setText(_translate("ChatRoom", ""))
        self.pushButton.setText(_translate("ChatRoom", "发送"))
        self.toolButton_3.setText(_translate("ChatRoom", ""))
        self.toolButton_4.setText(_translate("ChatRoom", ""))
from qfluentwidgets import ListWidget, PlainTextEdit, PushButton, TransparentToolButton, FluentIcon
